### ISSUE TITLE
Hello.

### ISSUE THREAD

**Issue by KittyNeverDies** [LTGVE/LTGVE#1]
Hello!

I wrote you an email about your repository, which was located here: `https://github.com/LTGVE/LiquidSensePlusPlusPlusPlus/`.

What happened to it? Can you recover it? Also, can I get the files from this repository?

Thank you in advance for any answers you can provide.

kittyneverdies

**Comment by LTGVE** [comment]
Hello，
I closed this repository for some reason.
Now I'll leave him open for a week, and after a week he'll delete it completely, and never revert.
Good luck.

**Comment by KittyNeverDies** [comment]
谢谢
